### ISSUE TITLE
[enhancement] Allow fqdn instead of (or in addition to) IP address

### ISSUE THREAD

**Issue by gregorlarson** [tihomir-kit/auto-wol#1]
Some home gateways (like my D-Link DIR-835) can be convinced to forward WOL packets to the LAN broadcast address. I use dynamic DNS to assign a name (FQDN) for my home WAN address.

Currently only an IP address is accepted for the destination address, not an FQDN.

If I enter the my home WAN IP address into auto-wol, I can wake a machine at home using my cell data plan (Virgin Mobile/Bell Canada), however, it would better if I could use the FQDN instead of the IP address.

**Comment by tihomir-kit** [comment]
Hi,

yes, I've delayed this for a bit too long now. I'll implement it for the weekend. Thanks for reminding me. :)

**Comment by tihomir-kit** [comment]
Hey, I'm working on this ATM. Unfortunately my current network setup does not allow me to properly test this. Would you perhaps be willing to test the new build and give me some feedback whether it works properly or not before I push it to gPlay?

I could add the build to either github or I could send it to you over email or whatever suits you.

**Comment by gregorlarson** [comment]
Sure attach it to the email.

**Comment by gregorlarson** [comment]
Tested version 1.0.8 from Google Play:
- test 1 (tested with nexus 7 kitkat 4.4.4 wifi)
  - worked with an FQDN which resolved to a broadcast address 10.1.0.255 on local LAN.
- test 2 (galaxy S3 kitkat 4.4.2, LTE data, Virgin Mobile Canada/Bell Canada network)
  - worked with a dynamic FQDN which resolves to my home gateway WAN address (custom port) that forwards to 10.1.0.255 port 9 on my local LAN.

Thanks!
